### PR TITLE
Icon suggestion

### PR DESCRIPTION
**Pull request by LoveIsGrief**
Hi, I just wanted to throw out suggestions for the icon if that's OK.

I'm no graphic designer, so here are only 2 suggestions:

| 128 | 64 | 32 | 24 |
| --- | --- | --- | --- |
| ![icon_128] |  ![icon_64] |  ![icon_32] |  ![icon_24]|

| 128 | 64 | 32 | 24 |
| --- | --- | --- | --- |
| ![icon_µ_128] |  ![icon_µ_64] |  ![icon_µ_32] |  ![icon_µ_24]|

[icon_µ_128]: https://user-images.githubusercontent.com/2829538/72357600-84b6ac00-36eb-11ea-929c-4ec4b323ef26.png
[icon_µ_64]: https://user-images.githubusercontent.com/2829538/72357605-86806f80-36eb-11ea-9156-71b3683a01d2.png
[icon_µ_32]: https://user-images.githubusercontent.com/2829538/72357609-884a3300-36eb-11ea-84f0-fd0081d1d735.png
[icon_µ_24]: https://user-images.githubusercontent.com/2829538/72357612-897b6000-36eb-11ea-9243-2278793dbb6c.png

[icon_128]: https://user-images.githubusercontent.com/2829538/72357594-808a8e80-36eb-11ea-9217-120ad85b38d5.png
[icon_64]: https://user-images.githubusercontent.com/2829538/72357575-79fc1700-36eb-11ea-8423-fb6c485910b7.png
[icon_32]: https://user-images.githubusercontent.com/2829538/72357585-7e283480-36eb-11ea-95b4-27648a2b824a.png
[icon_24]: https://user-images.githubusercontent.com/2829538/72357564-75cff980-36eb-11ea-9502-13e9e888a98c.png

I made it with an SVG in order for further editing down the line

### CODE REVIEW

**Comment by zlatinb** [comment]
It's all about messaging; the logo needs to reflect the message of the product.  I haven't actually decided what the message is yet; my choice for the current logo was to have something minimalist because at the time there was only the Swing GUI which had the bare minimum set of features to do file sharing.  But a lot has changed since then - there are many new features which go beyond simple file sharing and there is a plugin whose UI is significantly more polished.  So a new logo needs to reflect those characteristics.

I've been through a branding exercise once, and picking a logo can be a very tedious process with a lot of back-and-forth between those involved.  I'll leave this PR open for discussion on the topic.

**Comment by LoveIsGrief** [comment]
The logo was just a play on [Mu](https://en.wikipedia.org/wiki/Mu_\(letter\)) = µ and wires. Or it could just be a fancy µ, fancy wires or both.

Are you ok with that premise?

I don't mind the idea being rejected :slightly_smiling_face: It's not my area of expertise anyway. Maybe if you ask for help on HackerNews you might get someone with more skills.

**Comment by zlatinb** [comment]
Yes µ should be there but it must be different than the one in uTorrent.  Beyond that I'm very weak at visual stuff myself.  I'll ask around for help.

**Comment by IndiumGithub** [comment]
I'm not all too good with designing stuff but this is the best I've come up with
icon128
icon64
icon32
icon24

**Comment by zlatinb** [comment]
@IndiumGithub thanks for the suggestion.  I like that it's simple yet thoughtful.

**Comment by danrobi11** [comment]
Hello
Im suggesting something with MµW

**Comment by Shoalsteed** [comment]
image
image

**Comment by Shoalsteed** [comment]
Lots of great ideas! Above are my attempts.

**Comment by zlatinb** [comment]
Thanks to everyone who submitted so far.  Be aware that very soon MuWire may get re-licensed to "Public Domain", so make sure you're ok with your icon being licensed that way.

**Comment by Shoalsteed** [comment]
image

**Comment by LoveIsGrief** [comment]
I like that one @Shoalsteed . I tried mofifying it a little to make it reminiscent of a LAN port.

icon_hills_128
icon_thin_hills_256

**Comment by Shoalsteed** [comment]
image

**Comment by Shoalsteed** [comment]
muteal copy

**Comment by zlatinb** [comment]
Closing this, I got a logo I quite like.  It's already on the website and will be in the desktop client and plugin the next release.

**Pull request closed without merging**
