### PR TITLE
Docker image

### LINKED ISSUE #32: Docker image
It would be nice to have a docker image / Dockerfile to make this project available on [DockerHub](https://hub.docker.com/).

With the correct options it would be possible to contain MuWire and easily distribute it. Once work is done on the WebUI it would also be perfect to run on a server side-by-side with I2P.

### PR DESCRIPTION
**Pull request by LoveIsGrief**
This PR adds a docker image in order to run MuWire in its own service/container. 

An [image exists for my repo](https://hub.docker.com/repository/docker/bisentenialwrug/muwire), but once you create an account on Docker Hub, you'll have official MuWire releases.

The size might be able to be reduced in future releases with a modularized JRE.

TODO:

 - [x] Decide how to treat incompletes (by default saved in `/muwire/.MuWire/incompletes`)
  - Default `MuWire.properties` in docker?
  - **Docker volume for `/incompletes`? https://github.com/zlatinb/muwire/pull/33/commits/c910a215f524973ca95f77b05aaba632c2032f06**
 - [x] Try and find out if defaults can be used for i2p.properties in order to remove `i2cp.tcp.port=7654` requirement
  - **Implemented in https://github.com/zlatinb/muwire/pull/33/commits/65e073b1b952a497c074a773c186c7ab3de92a7d**

Closes #32

### CODE REVIEW

**Comment by LoveIsGrief** [comment]
Could I get a little help though? The MuWire starts well in Docker, but it doesn't seem to do anything else and this is what I see

afbeelding

No logs are written even if I copy rename https://github.com/zlatinb/muwire/blob/master/logging/4_logging.properties into $HOME/.MuWire

**Comment by zlatinb** [comment]
Thank you very much for your work.  I know next to nothing about docker but will try to learn more from your PR.

One important thing I need to ask you before accepting the PR has to do with the license.  Right now MuWire is GPLv3 but I am considering re-licensing it under public domain.  That way it will be able to be included by default with the I2P router.  I have received informal permission from all contributors to the "core' module as well as the "webui" and "plug" modules.  Are you ok with your work being released under Public Domain license?  Even if the answer is no I may still be able to accept the PR but it becomes more complicated as I will need to license the different components differently.

**Comment by zlatinb** [comment]
A general comment about the web ui and the docker image:  This is a bit complicated as the web ui currently works only as a plugin to the I2P router.  So, a fully self-contained docker image must contain the JRE, the I2P router with the plugin installed by default.

Unfortunately to my knowledge there is no way of making plugins install by default (will need to double-check with the i2p devs on that).  

Another complicating factor is that the router will only install plugins which are signed and whose public keys are present in the router "certificates" directory.  That's not a problem in itself because whoever builds the docker image can choose what certificates to include, but building and signing the plugin will be difficult to automate - it may require including the password to the signing key in some build file.  

I invite you to try and build the plugin as per the instructions on the wiki and let me know what you think about how feasible it would be to build a fully automated docker image.

**Comment by zlatinb** [comment]
Hi,

The 4_logging.properties should be in PWD from wherever MuWire is
launched.  If you are launching the embedded router, startup can take a
considerable amount of time.  Also if using the embedded router you need to
copy the reseed certificates from the I2P distribution, otherwise initial
bootstrap into the network will take forever (which is probably what is
happening here).

Take a look at the mw-pkg project (linked from the README.md) and the
various scripts that are referenced in that project.

**Comment by LoveIsGrief** [comment]
OK, it finally works

afbeelding

Still gotta add some TODOs

**Comment by zlatinb** [comment]
Impressive!  I'm on the road atm but as soon as I'm back home at my main workstation I'll look in detail at your work.  Please answer my question re: licensing above.

**Comment by LoveIsGrief** [comment]
Oh, hi @zlatinb 

Sorry, I hadn't refreshed my page and didn't see your responses before updating. Anyway, it works and I'd be glad for this to be public domain.

It's not necessary to worry about the web-ui and docker anymore. The GUI is started in docker and accessible through VNC on a webpage. I hope the README can get you up and running with the same results.

I have only considered the usecase of I2P running on the host and MuWire accessing it over the docker network interface. No consideration has be given to running I2P in the docker container. I think I2P should be run in a separate container in order to be able to update MuWire without restarting I2P too.

If something isn't clear in the PR, please don't hesitate to ask questions. Feedback is welcome and I'll do my best to make the README usable.

**Comment by zlatinb** [comment]
I see what you're trying to do with the incompletes folder and the right solution is to prompt the user on startup where the incomplete files should be stored.  (That's what the plugin does right now.)

Is it possible to do a symlink hack for the docker image?  If a `MuWire.properties` file is included in the image MW is not going to prompt the user for a nickname so that's not a feasible option.

**Comment by LoveIsGrief** [comment]
> Is it possible to do a symlink hack for the docker image?

Not sure what you mean by that.

> the right solution is to prompt the user on startup where the incomplete files should be stored [...]. If a `MuWire.properties` file is included in the image MW is not going to prompt the user for a nickname

Could another solution be to prompt the user for a nickname only when it's missing from the config? That would reduce the number of dialogs from 3 (nickname, download, incompletes) to 1 (nickname) and allow providing a default config.

**Comment by zlatinb** [comment]
> Could another solution be to prompt the user for a nickname only when it's missing from the config? That would reduce the number of dialogs from 3 (nickname, download, incompletes) to 1 (nickname) and allow providing a default config.

That might work, need to take a look, but even if it works it will be a solution only for the docker use case.  I'll try to implement this solution first to unblock you.

Instead of having 3 dialogs I was thinking of building a composite welcome dialog that allows choosing of nickname, downloads and incompletes locations on a single window, but that is a little tricky with the griffon framework.  Should be doable though.

**Comment by LoveIsGrief** [comment]
OK, great. I shall wait on your development :slightly_smiling_face: 

Thanks for the quick responses. I hope this gets merged someday in order to me (and maybe others) to join the MuWire network.

**Comment by zlatinb** [comment]
> OK, great. I shall wait on your development 🙂

Done in latest commit.  You should be able to include a `MuWire.properties` without a `nickname` entry and MW will prompt for a nickname.  Please test.

> Thanks for the quick responses. I hope this gets merged someday in order to me (and maybe others) to join the MuWire network.

I will wait for you to give the green light for merging, review and learn about docker in the process and merge.  I imagine I need to create an account on Docker Hub for this to become publicly available?

**Comment by LoveIsGrief** [comment]
Indeed, you'll need to create an account on Docker Hub. It'll need to be added to the `docker run` command in the README to replace  "bisentenialwrug/muwire"

I'm just adding the finishing touches in order for Docker Hub to tag the images correctly.

**Comment by LoveIsGrief** [comment]
Alright. PR should be ready now.

Your modifications are working well. Thank you for the quick participation.

**Comment by zlatinb** [comment]
Thanks.  I took a quick look over the changed files and it seems almost exclusively docker-specific changes, so I don't mind merging.  

Does the incompletes warning and screenshot still matter after the inclusion of a default `MuWire.properties` ?

Also, I will move the docker info to a wiki page after merging; I try to keep the README.md to the bare minimum.

**Comment by LoveIsGrief** [comment]
> Does the incompletes warning and screenshot still matter after the inclusion of a default MuWire.properties ?

Indeed it doesn't. I'll get rid of that right now.

> Also, I will move the docker info to a wiki page after merging; I try to keep the README.md to the bare minimum.

I think at least a link should be added otherwise people on Docker Hub won't know where to look.

Don't forget to replace `bisentenialwrug/muwire` with your docker hub repo in the README/wiki once it's been created :wink:

**Comment by zlatinb** [comment]
I think I've set up the build hooks wrong.  I added you as a collaborator on dockerhub, can you take a look and see what I'm doing wrong?

I basically have two rules - one for `muwire-x.y.z` tags which will be used for production builds, and another for `docker-x.y.z` tags to use while I get it to work.

**Comment by zlatinb** [comment]
ok, building from master works when I force start it, but it's not picking up my tag rules

**Comment by LoveIsGrief** [comment]
I'm also new to using tags for building on DockerHub, but after a few tests, it seems like you need to have a tag within the pushed changesets in order for it to trigger.

I updated the repo on docker hub, however the tag will be the version number directly in order for users to be able to do `docker pull zlatinb/muwire:0.6.8` instead of `docker pull zlatinb/muwire:muwire-0.6.8`.

So, if you create a new commit and tag it, it should work.

**Pull request merged**
